### ISSUE TITLE
Temporary files can't be moved if on a different disk

### ISSUE THREAD

**Issue by Keagel** [WyattBlue/auto-editor#113]
**What went wrong**

```
❯ auto-editor "/mnt/d/Users/PC/Videos/2020-12-10 08-03-14.mkv" --edit_based_on audio_or_motion --frame_margin 90 --export_to_premiere --keep_tracks_seperate --debug

  Exporting to Adobe Premiere Pro XML file.
   - Temp Directory: /tmp/tmpmkb68y3o
   - Speeds: [99999, 1.0]
   - INPUT_FILE: /mnt/d/Users/PC/Videos/2020-12-10 08-03-14.mkv
   - newOutput: /mnt/d/Users/PC/Videos/2020-12-10 08-03-14.xml
   - sampleRate: 48000
   - audioBitrate: None
   - Frame Rate: 29.97
Analyzing audio volume.
Analyzing video motion.
   - Cutting totalFrames: 213254
audioList Length:  213040
motionList Length: 213254
Reducing the size of motionList to match audioList.
tracks: 6
/mnt/d/Users/PC/Videos/Cours
Traceback (most recent call last):
  File "/usr/local/bin/auto-editor", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/auto_editor/__main__.py", line 474, in main
    exportToPremiere(INPUT_FILE, TEMP, newOutput, clips, tracks, sampleRate,
  File "/usr/local/lib/python3.8/dist-packages/auto_editor/premiere.py", line 78, in exportToPremiere
    os.rename(os.path.join(temp, f'{i}.wav'), newtrack)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpmkb68y3o/1.wav' -> '/mnt/d/Users/PC/Videos/2020-12-10 08-03-14_tracks/1.wav'
```

I assume this is due to os.rename not being able to handle the source and destination paths being on different disks.

**Comment by Keagel** [comment]
Replacing `os.rename` with `shutil.move` solves the problem.

**Comment by WyattBlue** [comment]
Fixed in 20w51a
