### ISSUE TITLE
ValueError: cannot reshape array of size 30935001 into shape (2)

### ISSUE THREAD

**Issue by shojaeix** [WyattBlue/auto-editor#116]
Hi, i think there is a small bug here

The version: 20w52a

First, i executed a command, but i failed with error 

```
Creating new video: [████████████████░░░░░░░░░░░░░░░░░░░] 45.2% done ETA 02:31 PM               ░░░░░░░░░░░░░] 45.2% done ETA 02:31 PM                   ⏳Creating new video: [█████████████████░░░░░░░░░░░░░░░░░░] 47.3% done ETA 02:31 PM                 ⏳Creating new video: [█████████████████░░░░░░░░░░░░░░░░░░] 47.3% done ETA   ⏳Creating new video: [█████████████████░░░░░░░░░░░░░░░░░░] 47.3% done ETA   ⏳Creating new video: [█████████████████░░░░░░░░░░░░░░░░░░] 47.3% done ETA   ⏳Creating new video: [█████████████████░░░░░░░░░░░░░░░░░░] 47.3% done ETA   ⏳Creating new video: [█████████████████░░░░░░░░░░░░░░░░░░] 47.3% done ETA   ⏳Creating new video: [█████████████████░░░░░░░░░░░░░░░░░░] 47.3% done ETA   ⏳Creating new video: [█████████████████░░░░░░░░░░░░░░░░░░] 47.3% done ETA   ⏳Creating new video: [█████████████████░░░░░░░░░░░░░░░░░░] 47.3% done ETA   ⏳Creating new video: [█████████████████░░░░░░░░░░░░░░░░░░] 47.3% done ETA 

Error! The file e4.mp4 was not created.                                     
```

But when I executed another command with same output file name, i received this error:
```
Traceback (most recent call last):                                                                                                                         
  File "auto-editor", line 8, in <module>
    sys.exit(main())
  File "lib/python3.8/site-packages/auto_editor/__main__.py", line 404, in main
    sampleRate, audioData = read(f'{TEMP}/{args.cut_by_this_track}.wav')
  File "lib/python3.8/site-packages/auto_editor/wavfile.py", line 553, in read
    data = _read_data_chunk(fid, format_tag, channels, bit_depth,
  File "lib/python3.8/site-packages/auto_editor/wavfile.py", line 455, in _read_data_chunk
    data = data.reshape(-1, channels)
ValueError: cannot reshape array of size 30935001 into shape (2)

```

The example video works, also when i changed the output file name, it started to work again.

**debug info**

```
Python Version: 3.8.5 64-bit
Platform: Linux 5.4.0-58-generic
FFmpeg path: ffmpeg
FFmpeg version: 4.2.4-1ubuntu0.1
Auto-Editor version 20w52a
```

**Comment by WyattBlue** [comment]
Thanks for the report, I'll look into it soon.

**Comment by WyattBlue** [comment]
See, if this error still occurs in the latest version. I've gotten around to testing auto-editor with a variety of audio codecs and various files and while I never encountered this exact bug, I fixed a lot more.
