### ISSUE TITLE
Crash when using info on a mkv file

### ISSUE THREAD

**Issue by WyattBlue** [WyattBlue/auto-editor#124]
When running the info command on a mkv container video, the program crashed for some reason.

```
auto-editor info test.mkv
```

```
file: /Users/wyattblue/projects/auto-editor/resources/test.mkv
 - fps: 30.0
 - resolution: 1280x720
Traceback (most recent call last):
  File "/usr/local/bin/auto-editor", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/auto_editor/__main__.py", line 269, in main
    getInfo(args.input, ffmpeg, ffprobe, log)
  File "/usr/local/lib/python3.9/site-packages/auto_editor/info.py", line 31, in getInfo
    vbit = str(int(int(raw_data[1]) / 1000)) + 'k'
ValueError: invalid literal for int() with base 10: 'N/A\n'
```

**Comment by WyattBlue** [comment]
Fix was pretty easy. Just had to make sure `raw_data[1]` was numeric before doing any operations on it, if not, display N/A as the video bitrate.
