### ISSUE TITLE
BrokenPipeError while using the arguments --video_codec h264

### ISSUE THREAD

**Issue by filvi** [WyattBlue/auto-editor#145]
(Make sure you're using the latest version)

**What went wrong**
I got BrokenPipeError while trying to use `auto-editor <filepath> --video_codec h264`

```
Traceback (most recent call last):
  File "c:\users\the-machine\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\the-machine\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\the-machine\AppData\Local\Programs\Python\Python39\Scripts\auto-editor.exe\__main__.py", line 7, in <module>
    import tempfile
  File "c:\users\the-machine\appdata\local\programs\python\python39\lib\site-packages\auto_editor\__main__.py", line 668, in main
    renderAv(ffmpeg, ffprobe, INPUT_FILE, args, chunks, speeds, fps,
  File "C:\Users\the-machine\AppData\Local\Programs\Python\Python39\Lib\site-packages\auto_editor\renderVideo.py", line 77, in renderAv
    process2.stdin.write(in_bytes)
BrokenPipeError: [Errno 32] Broken pipe
```

**Does the example video work? (if applicable)**
I tryed with different files, same results

**What does the program output when `--debug` or `--show_ffmpeg_debug` is appended to your command/use case**

#--debug#
```
Traceback (most recent call last):░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0.0% done ETA 12:10 PM
  File "c:\users\the-machine\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\the-machine\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\the-machine\AppData\Local\Programs\Python\Python39\Scripts\auto-editor.exe\__main__.py", line 7, in <module>
    import tempfile
  File "c:\users\the-machine\appdata\local\programs\python\python39\lib\site-packages\auto_editor\__main__.py", line 668, in main
    renderAv(ffmpeg, ffprobe, INPUT_FILE, args, chunks, speeds, fps,
  File "C:\Users\the-machine\AppData\Local\Programs\Python\Python39\Lib\site-packages\auto_editor\renderVideo.py", line 77, in renderAv
    process2.stdin.write(in_bytes)
BrokenPipeError: [Errno 32] Broken pipe

C:\Users\the-machine>auto-editor "C:\xampp\htdocs\MediaServer\Videos\DataVisualizationLab\2. lecture\Feb23_TH.mp4" --debug --video_codec h264

   - Temp Directory: C:\Users\THE-MA~1\AppData\Local\Temp\tmpkcuo617l
   - Speeds: [99999, 1.0]
   - INPUT_FILE: C:\xampp\htdocs\MediaServer\Videos\DataVisualizationLab\2. lecture\Feb23_TH.mp4
   - newOutput: C:\xampp\htdocs\MediaServer\Videos\DataVisualizationLab\2. lecture\Feb23_TH_ALTERED.mp4
['C:\\Users\\the-machine\\AppData\\Local\\Programs\\Python\\Python39\\Lib\\site-packages\\auto_editor\\win-ffmpeg\\bin\\ffprobe.exe', '-v', 'error', '-select_streams', 'a:0', '-show_entries', 'stream=sample_rate', '-of', 'compact=p=0:nk=1', 'C:\\xampp\\htdocs\\MediaServer\\Videos\\DataVisualizationLab\\2. lecture\\Feb23_TH.mp4']
32000

   - sampleRate: 32000
['C:\\Users\\the-machine\\AppData\\Local\\Programs\\Python\\Python39\\Lib\\site-packages\\auto_editor\\win-ffmpeg\\bin\\ffprobe.exe', '-v', 'error', '-select_streams', 'a:0', '-show_entries', 'stream=bit_rate', '-of', 'compact=p=0:nk=1', 'C:\\xampp\\htdocs\\MediaServer\\Videos\\DataVisualizationLab\\2. lecture\\Feb23_TH.mp4']
126250

   - audioBitrate: 126k
['C:\\Users\\the-machine\\AppData\\Local\\Programs\\Python\\Python39\\Lib\\site-packages\\auto_editor\\win-ffmpeg\\bin\\ffprobe.exe', '-v', 'error', '-select_streams', 'v', '-show_entries', 'stream=r_frame_rate', '-of', 'compact=p=0:nk=1', 'C:\\xampp\\htdocs\\MediaServer\\Videos\\DataVisualizationLab\\2. lecture\\Feb23_TH.mp4']
25/1

['C:\\Users\\the-machine\\AppData\\Local\\Programs\\Python\\Python39\\Lib\\site-packages\\auto_editor\\win-ffmpeg\\bin\\ffprobe.exe', '-v', 'error', '-select_streams', 'a', '-show_entries', 'stream=index', '-of', 'compact=p=0:nk=1', 'C:\\xampp\\htdocs\\MediaServer\\Videos\\DataVisualizationLab\\2. lecture\\Feb23_TH.mp4']
0

['C:\\Users\\the-machine\\AppData\\Local\\Programs\\Python\\Python39\\Lib\\site-packages\\auto_editor\\win-ffmpeg\\bin\\ffmpeg.exe', '-y', '-i', 'C:\\xampp\\htdocs\\MediaServer\\Videos\\DataVisualizationLab\\2. lecture\\Feb23_TH.mp4', '-ab', '126k', '-ac', '2', '-ar', '32000', '-map', '0:a:0', 'C:\\Users\\THE-MA~1\\AppData\\Local\\Temp\\tmpkcuo617l\\0.wav', '-nostats', '-loglevel', '8']
   - Frame Rate: 25.0
Analyzing audio volume.
  ⏳Creating new audio: [█████████████████████████████████████████████████] 100% done ETA 12:13 PM
   - Total Samples: 108551679
   - Samples per Frame: 1280.0
   - Expected video length: 84805.99921875
Using av method
   - pix_fmt: yuv420p: [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% done ETA 12:13 PM
Traceback (most recent call last):░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0.0% done ETA 12:13 PM
  File "c:\users\the-machine\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\the-machine\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\the-machine\AppData\Local\Programs\Python\Python39\Scripts\auto-editor.exe\__main__.py", line 7, in <module>
    import tempfile
  File "c:\users\the-machine\appdata\local\programs\python\python39\lib\site-packages\auto_editor\__main__.py", line 668, in main
    renderAv(ffmpeg, ffprobe, INPUT_FILE, args, chunks, speeds, fps,
  File "C:\Users\the-machine\AppData\Local\Programs\Python\Python39\Lib\site-packages\auto_editor\renderVideo.py", line 77, in renderAv
    process2.stdin.write(in_bytes)
BrokenPipeError: [Errno 32] Broken pipe
```

#--show_ffmpeg_debug#
```
Track data: ['0']
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\xampp\htdocs\MediaServer\Videos\DataVisualizationLab\2. lecture\Feb23_TH.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2021-02-23T12:03:20.000000Z
  Duration: 01:21:27.96, start: 0.000000, bitrate: 198 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 32000 Hz, mono, fltp, 126 kb/s (default)
    Metadata:
      creation_time   : 2021-02-23T12:03:20.000000Z
      handler_name    : AAC audio
    Stream #0:1(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1680x1050, 69 kb/s, 25 fps, 25 tbr, 30k tbn, 60k tbc (default)
    Metadata:
      creation_time   : 2021-02-23T12:03:20.000000Z
      handler_name    : H.264/AVC video
      encoder         : AVC Coding
Stream mapping:
  Stream #0:0 -> #0:0 (aac (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'C:\Users\THE-MA~1\AppData\Local\Temp\tmp2jxxyzgr\0.wav':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    ISFT            : Lavf58.45.100
    Stream #0:0(und): Audio: pcm_s16le ([1][0][0][0] / 0x0001), 32000 Hz, stereo, s16, 1024 kb/s (default)
    Metadata:
      creation_time   : 2021-02-23T12:03:20.000000Z
      handler_name    : AAC audio
      encoder         : Lavc58.91.100 pcm_s16le
size=  610992kB time=01:21:27.93 bitrate=1024.0kbits/s speed=2.22e+03x
video:0kB audio:610992kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000012%
ffmpeg version 4.3 Copyright (c) 2000-2020 the FFmpeg developers░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% done ETA 12:14 PM
  built with gcc 9.3.1 (GCC) 20200621
  configuration: --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libaom --enable-libgsm --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-libopenmpt --enable-amf
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
Input #0, rawvideo, from 'pipe:':
  Duration:   ⏳Creating new video: [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0.0% done ETA 12:14 PM        N/A, start: 0.000000, bitrate: 529200 kb/s
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1680x1050, 529200 kb/s, 25 tbr, 25 tbn, 25 tbc
Codec AVOption crf (Select the quality for constant quality mode) specified for output file #0 (C:\Users\THE-MA~1\AppData\Local\Temp\tmp2jxxyzgr\spedup.mp4) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Codec AVOption preset (Configuration preset) specified for output file #0 (C:\Users\THE-MA~1\AppData\Local\Temp\tmp2jxxyzgr\spedup.mp4) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (h264_amf))
[h264_amf @ 0000017e8d312a00] DLL amfrt64.dll failed to open
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
Traceback (most recent call last):
  File "c:\users\the-machine\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\the-machine\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\the-machine\AppData\Local\Programs\Python\Python39\Scripts\auto-editor.exe\__main__.py", line 7, in <module>
    import tempfile
  File "c:\users\the-machine\appdata\local\programs\python\python39\lib\site-packages\auto_editor\__main__.py", line 668, in main
    renderAv(ffmpeg, ffprobe, INPUT_FILE, args, chunks, speeds, fps,
  File "C:\Users\the-machine\AppData\Local\Programs\Python\Python39\Lib\site-packages\auto_editor\renderVideo.py", line 77, in renderAv
    process2.stdin.write(in_bytes)
BrokenPipeError: [Errno 32] Broken pipe
```

**What's your platform? (if applicable)**
Windows 10 Pro
```
output here, run: `auto-editor --debug` if possible.
Python Version: 3.9.2 64-bit
Platform: Windows 10
Config File path: C:\Users\the-machine\AppData\Local\Programs\Python\Python39\Lib\site-packages\auto_editor\config.txt
FFmpeg path: C:\Users\the-machine\AppData\Local\Programs\Python\Python39\Lib\site-packages\auto_editor\win-ffmpeg\bin\ffmpeg.exe
FFmpeg version: 4.3
Auto-Editor version 21w08a
```

**What's your input? (if applicable)**

```
output here, run: `auto-editor info path/to/video
file: C:\xampp\htdocs\MediaServer\Videos\DataVisualizationLab\2. lecture\Feb23_TH.mp4
 - fps: 25.0
   - mode: VFR:0.000000 (0/122198)
 - duration: 4887.96
 - resolution: 1680x1050 (8:5)
 - video codec: h264
 - video bitrate: 70k
 - audio tracks: 1
   - Track #0
     - codec: aac
     - samplerate: 32.0 kHz
     - bitrate: 126k
```

**Comment by WyattBlue** [comment]
I fixed this a while ago where it would display the actual error instead of giving a generic `BrokenPipeError`

Try the new version.
```
pip3 install -U auto-editor
```
