### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by callmedougan** [WyattBlue/auto-editor#16]
i suspect i've fallen folly of my complete newbishness of python but i've come unstuck  with running the basic code 

```
python auto-editor.py example.mp4
Running from fastVideo.py
Traceback (most recent call last):
  File "auto-editor.py", line 172, in <module>
    FRAME_SPREADAGE, SAMPLE_RATE)
  File "C:\python\GitHub\auto-editor-master\scripts\fastVideo.py", line 74, in fastVideo
    timeTaken = getVideoLength(videoFile) / 5
  File "C:\python\GitHub\auto-editor-master\scripts\fastVideo.py", line 66, in getVideoLength
    stderr=subprocess.STDOUT)
  File "C:\Python\python37 64bit\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python\python37 64bit\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Python\python37 64bit\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

can safely say the requirements.txt have been installed

```
C:\python\GitHub\auto-editor-master> pip3 install scipy audiotsm pillow pydub opencv-python youtube_dl
Requirement already satisfied: scipy in c:\users\andrew\appdata\roaming\python\python37\site-packages (1.4.1)
Requirement already satisfied: audiotsm in c:\python\python37 64bit\lib\site-packages (0.1.2)
Requirement already satisfied: pillow in c:\python\python37 64bit\lib\site-packages (7.1.1)
Requirement already satisfied: pydub in c:\python\python37 64bit\lib\site-packages (0.23.1)
Requirement already satisfied: opencv-python in c:\python\python37 64bit\lib\site-packages (4.2.0.34)
Requirement already satisfied: youtube_dl in c:\python\python37 64bit\lib\site-packages (2020.6.6)
Requirement already satisfied: numpy>=1.13.3 in c:\users\andrew\appdata\roaming\python\python37\site-packages (from scipy) (1.18.2)
```

any advise for a newbie on where next to debug ?

**Comment by WyattBlue** [comment]
It never hurts to run ``` auto-editor.py --debug```

**Comment by callmedougan** [comment]
this goes to show how much of a newbie i am (forgetting to put the debug report in the initial post)

```
C:\python\GitHub\auto-editor-master> python auto-editor.py --debug
Python Version:
3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
Is your python 64-Bit?
True
Auto-Editor Version:
20w24b
```

**Comment by WyattBlue** [comment]
I released a fix that should solve your problem, along with some other bug fixes. 
Try using that.

**Comment by callmedougan** [comment]
downloaded the newer bundle and getting similar problems

```
PS C:\python\GitHub\auto-editor-master> python auto-editor.py --debug
Python Version:
3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
Is your python 64-Bit?
True
Auto-Editor Version:
20w24b hotfix
```
the debug statement


```
PS C:\python\GitHub\auto-editor-master> python auto-editor.py example.mp4
Running from fastVideo.py
Traceback (most recent call last):
  File "C:\python\GitHub\auto-editor-master\scripts\fastVideo.py", line 67, in getVideoLength
    stderr=subprocess.STDOUT)
  File "C:\Python\python37 64bit\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python\python37 64bit\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Python\python37 64bit\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "auto-editor.py", line 202, in <module>
    FRAME_SPREADAGE, SAMPLE_RATE, VERBOSE)
  File "C:\python\GitHub\auto-editor-master\scripts\fastVideo.py", line 78, in fastVideo
    vidLength = getVideoLength(videoFile)
  File "C:\python\GitHub\auto-editor-master\scripts\fastVideo.py", line 69, in getVideoLength
    except(e):
NameError: name 'e' is not defined
```
the update error


~~~ 

daft question i assume python 3.7.7 versus 3.8.3 wouldnt cause this discrepancy, if so i'll go nab the latest (stable) version

**Comment by WyattBlue** [comment]
This erro can be avoided if you have set ffprobe to your path correctly. You can check by running this.

```terminal
$ ffprobe -version
```

This issue is solved.
