### ISSUE TITLE
Kdenlive export

### ISSUE THREAD

**Issue by jedenastka** [WyattBlue/auto-editor#170]
I would want to have an `--export_to_kdenlive` option that exports to the [Kdenlive project format](https://kdenlive.org/en/project/kdenlive-project-file-format/).

I want this feature to be added, because this project is basically useless to me, even though I think the idea is interesting, since I can't use it with my preffered video editor.

This might be related to #167 since the Kdenlive format is basically glorified MLT. Kdenlive even supports MLT import, but you cannot adjust cuts in MLT clips (they appear as a single, uncut video), so ideally both formats would be added.

**Comment by carlosmatthews** [comment]
not is possible import a xml file in kdenlive?
according to its web page, you could import an xml for premiere or final cut, in this version.
check this link..

https://kdenlive.org/en/2020/04/kdenlive-20-04-is-out/

**Comment by jedenastka** [comment]
Yeah, Kdenlive supports [OpenTimelineIO](https://github.com/PixarAnimationStudios/OpenTimelineIO), which is a project that allows conversion to and from various formats.

OTIO is, however, beta-quality software, and doesn't really work well... if it works at all, which isn't the case with converting auto-editor generated files to Kdenlive's MLT:

```
~/tymczasowe/autoeditor_test $ auto-editor 2021-03-04\ 19-12-46.mkv --export_to_resolve
2021-03-04 19-12-46.mkvResolve XML file.                                       

Auto-Editor made 61 cuts, which would have taken about 30 minutes if edited manually.
~/tymczasowe/autoeditor_test $ otioconvert -i 2021-03-04\ 19-12-46.xml -o 2021-03-04\ 19-12-46_xml.kdenlive
Traceback (most recent call last):
  File "/home/grzesiek11/.local/bin/otioconvert", line 8, in <module>
    sys.exit(main())
  File "/home/grzesiek11/.local/pipx/venvs/opentimelineio/lib/python3.9/site-packages/opentimelineio/console/otioconvert.py", line 261, in main
    otio.adapters.write_to_file(
  File "/home/grzesiek11/.local/pipx/venvs/opentimelineio/lib/python3.9/site-packages/opentimelineio/adapters/__init__.py", line 191, in write_to_file
    return adapter.write_to_file(
  File "/home/grzesiek11/.local/pipx/venvs/opentimelineio/lib/python3.9/site-packages/opentimelineio/adapters/adapter.py", line 188, in write_to_file
    result = self.write_to_string(input_otio, **adapter_argument_map)
  File "/home/grzesiek11/.local/pipx/venvs/opentimelineio/lib/python3.9/site-packages/opentimelineio/adapters/adapter.py", line 255, in write_to_string
    return self._execute_function(
  File "/home/grzesiek11/.local/pipx/venvs/opentimelineio/lib/python3.9/site-packages/opentimelineio/plugins/python_plugin.py", line 174, in _execute_function
    return (getattr(self.module(), func_name)(**kwargs))
  File "/home/grzesiek11/.local/pipx/venvs/opentimelineio/lib/python3.9/site-packages/opentimelineio_contrib/adapters/kdenlive.py", line 224, in write_to_string
    'in': clock(clip.media_reference.available_range.start_time),
AttributeError: 'NoneType' object has no attribute 'start_time'
~/tymczasowe/autoeditor_test $ auto-editor 2021-03-04\ 19-12-46.mkv --export_to_final_cut_pro              
2021-03-04 19-12-46.mkvt Pro XML file.                                         
Auto-Editor made 61 cuts, which would have taken about 30 minutes if edited manually.
~/tymczasowe/autoeditor_test $ otioconvert -i 2021-03-04\ 19-12-46.fcpxml -o 2021-03-04\ 19-12-46_fcpxml.kdenlive
Traceback (most recent call last):
  File "/home/grzesiek11/.local/bin/otioconvert", line 8, in <module>
    sys.exit(main())
  File "/home/grzesiek11/.local/pipx/venvs/opentimelineio/lib/python3.9/site-packages/opentimelineio/console/otioconvert.py", line 261, in main
    otio.adapters.write_to_file(
  File "/home/grzesiek11/.local/pipx/venvs/opentimelineio/lib/python3.9/site-packages/opentimelineio/adapters/__init__.py", line 191, in write_to_file
    return adapter.write_to_file(
  File "/home/grzesiek11/.local/pipx/venvs/opentimelineio/lib/python3.9/site-packages/opentimelineio/adapters/adapter.py", line 188, in write_to_file
    result = self.write_to_string(input_otio, **adapter_argument_map)
  File "/home/grzesiek11/.local/pipx/venvs/opentimelineio/lib/python3.9/site-packages/opentimelineio/adapters/adapter.py", line 255, in write_to_string
    return self._execute_function(
  File "/home/grzesiek11/.local/pipx/venvs/opentimelineio/lib/python3.9/site-packages/opentimelineio/plugins/python_plugin.py", line 174, in _execute_function
    return (getattr(self.module(), func_name)(**kwargs))
  File "/home/grzesiek11/.local/pipx/venvs/opentimelineio/lib/python3.9/site-packages/opentimelineio_contrib/adapters/kdenlive.py", line 184, in write_to_string
    rate = input_otio.duration().rate
AttributeError: 'opentimelineio._otio.SerializableCollection' object has no attribute 'duration'
~/tymczasowe/autoeditor_test $ 
```

(Kdenlive reports similar errors, but less verbose).

**Comment by carlosmatthews** [comment]
Ah, ok..

**Comment by WyattBlue** [comment]
Kdenlive reports that it reports final cut pro 7 xml (premiere) so adding support for it specifically shouldn't be necessary

**Comment by Goldenlion5648** [comment]
It seems like kdenlive does not support those formats (maybe in an old version it did?) Or at least renaming the output from premiere export to have the .kdenlive extension does not seem to work

**Comment by WyattBlue** [comment]
Auto-Editor has added a native kdenlive exporter (`--export kdenlive`) in 2025.
