### ISSUE TITLE
auto-editor 21.19.1 crash Win10 to BSOD

### ISSUE THREAD

**Issue by wkwee** [WyattBlue/auto-editor#177]
pip version = python39\lib\site-packages (21.1.1)
when executing for silence cut, would falsely prompt, despite running both pip & auto-editor at latest rev: 
"Auto-Editor is out of date. Run:

    pip3 install -U auto-editor

to upgrade to the latest version."

Win10 crash to BSOD in a few seconds after the error prompt.
after several tries Win10 was corrupted required reformat (system installed since 2018).

issue reproduced after Windows 10 reinstallation.
Reverting back to auto-editor-21.16.1, eliminated crashing.

system config: i8700k + Nvidia GTX 1070, 32GB RAM.

**Comment by WyattBlue** [comment]
I also noticed that the upgrade message was being displayed even though it shouldn't, so I fixed that.

I ran the latest version on my Windows Installation and it didn't crash the os, so I'll need more details before I can look into that.

**Comment by wkwee** [comment]
upgraded to 21.19.2, when attempt silence cut, the following returned, good news is it now longer crash windows, but yield no video editing output nor XML:
H:\> auto-editor ".\2021-05-09 02-08-48.mp4" -exr
Warning! exportMediaOps options are not used when exporting  as an XML.
.\2021-05-09 02-08-48.mp4solve XML file.
Warning! Could not get number of VRF Frames.
Traceback (most recent call last):
  File "c:\users\wkwee\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\wkwee\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\wkwee\AppData\Local\Programs\Python\Python39\Scripts\auto-editor.exe\__main__.py", line 7, in <module>
    import tempfile
  File "c:\users\wkwee\appdata\local\programs\python\python39\lib\site-packages\auto_editor\__main__.py", line 557, in main
    sampleRate, audioData = read(f'{TEMP}{sep()}{args.cut_by_this_track}.wav')
  File "C:\Users\wkwee\AppData\Local\Programs\Python\Python39\Lib\site-packages\auto_editor\wavfile.py", line 551, in read
    data = _read_data_chunk(fid, format_tag, channels, bit_depth,
  File "C:\Users\wkwee\AppData\Local\Programs\Python\Python39\Lib\site-packages\auto_editor\wavfile.py", line 453, in _read_data_chunk
    data = data.reshape(-1, channels)
ValueError: cannot reshape array of size 14811097 into shape (2)
