### ISSUE TITLE
youtube-dl not working on 21w26a

### ISSUE THREAD

**Issue by daddyparodz** [WyattBlue/auto-editor#200]
(Make sure you're using the latest version)

auto-editor https://github.com/WyattBlue/auto-editor/raw/master/example.mp4 -m 0 -d

Paste the terminal output here
```
Debug: Temp Directory: C:\Users\Daddy\AppData\Local\Temp\tmpkc37vwr9
Traceback (most recent call last):░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 1.0% done ETA 12:17 AM
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Daddy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\auto-editor.exe\__main__.py", line 7, in <module>
  File "C:\Users\Daddy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\auto_editor\__main__.py", line 697, in main
    inputList, segments = valid_input(args.input, ffmpeg, args, log)
  File "C:\Users\Daddy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\auto_editor\validateInput.py", line 148, in valid_input
    new_inputs.append(download_video(my_input, args, ffmpeg, log))
  File "C:\Users\Daddy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\auto_editor\validateInput.py", line 96, in download_video
    'cookiefile': os.path.abspath(args.cookies),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\ntpath.py", line 527, in abspath
    return normpath(_getfullpathname(path))
TypeError: _getfullpathname: path should be string, bytes or os.PathLike, not NoneType

```

**Does the example video work? (if applicable)**
no

**What does the program output when `--debug` or `--show_ffmpeg_debug` is appended to your command/use case**
exactly what I pasted up here

output here:
```
Traceback (most recent call last):░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 1.0% done ETA 12:20 AM
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Daddy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\auto-editor.exe\__main__.py", line 7, in <module>
  File "C:\Users\Daddy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\auto_editor\__main__.py", line 697, in main
    inputList, segments = valid_input(args.input, ffmpeg, args, log)
  File "C:\Users\Daddy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\auto_editor\validateInput.py", line 148, in valid_input
    new_inputs.append(download_video(my_input, args, ffmpeg, log))
  File "C:\Users\Daddy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\auto_editor\validateInput.py", line 96, in download_video
    'cookiefile': os.path.abspath(args.cookies),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\ntpath.py", line 527, in abspath
    return normpath(_getfullpathname(path))
TypeError: _getfullpathname: path should be string, bytes or os.PathLike, not NoneType

**What's your platform? (if applicable)**

Windows 10

```
output here, run: `auto-editor --debug` if possible.
```
Python Version: 3.9.4 64-bit
Platform: Windows 10
Config File path: C:\Users\Daddy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\auto_editor\config.txt
FFmpeg path: C:\Users\Daddy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\auto_editor\ffmpeg\Windows\ffmpeg.exe
FFmpeg version: 4.3
Auto-Editor version 21w26a

```
**What's your input? (if applicable)**
none

output here, run: `auto-editor info path/to/video

INPUT:  ``` auto-editor info .\example.mp4 ```

OUTPUT:
```
file: .\example.mp4
 - fps: 30
 - duration: 00:00:42.45
 - resolution: 1280x720 (16:9)
 - video codec: h264
 - video bitrate: 240 kb/s
 - audio tracks: 1
   - Track #0
     - codec: aac
     - samplerate: 48000
     - bitrate: 317 kb/s

**Comment by daddyparodz** [comment]
Edit: I think it's a crash more than a bug because it throws a traceback. I'm sorry, can you change the label?

**Comment by WyattBlue** [comment]
Thanks @daddyparodz, I found that the issue was that `os.path.abspath` does not accept `None` values, I made a helper function:

```python
def abspath(path):
    if(path is None):
        return None
    return os.path.abspath(path)
```

and replaced `os.path.abspath` with that function when relevant, however, youtube-dl gets confused when some options in `ydl_opts` are `None`, so we need to sanitize that here:

```python
for item, key in ydl_opts.items():
    if(item is None):
        del ydl_opts[key]
```

I patched these changes into `master` recently, along with fixes for a few other issues, and added them to release 20w28a, available now.

**Comment by daddyparodz** [comment]
Thank you! You're awesome!
