### ISSUE TITLE
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by specialprograms** [WyattBlue/auto-editor#221]
When I run auto-edit C:\video I get the following error:

Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\username\AppData\Roaming\Python\Python39\Scripts\auto-editor.exe\__main__.py", line 7, in <module>
  File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\auto_editor\__main__.py", line 413, in main
    main_loop(input_list, ffmpeg, args, speeds, segments, log)
  File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\auto_editor\__main__.py", line 389, in main_loop
    inp = ffmpeg.file_info(input_path)
  File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\auto_editor\ffwrapper.py", line 178, in file_info
    return File(self, path)
  File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\auto_editor\ffwrapper.py", line 53, in __init__
    self.metadata[active_key] += '\n' + body
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

**Comment by WyattBlue** [comment]
Fixed in 21w50a
