### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '23.98'

### ISSUE THREAD

**Issue by specialprograms** [WyattBlue/auto-editor#224]
21w50a

Auto-editor crashed after running the command: auto-editor E:\P1100495.MOV --export_to_premiere

```
C:\WINDOWS\system32>auto-editor E:\P1100495.MOV --export_to_premiere
Traceback (most recent call last):XML file.
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\auto-editor.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\auto_editor\__main__.py", line 408, in main
    main_loop(input_list, ffmpeg, args, speeds, segments, log)
  File "c:\python39\lib\site-packages\auto_editor\__main__.py", line 389, in main_loop
    cuts, output_path = edit_media(i, inp, ffmpeg, args, progress, speeds,
  File "c:\python39\lib\site-packages\auto_editor\edit.py", line 136, in edit_media
    fps = int(inp.fps)
ValueError: invalid literal for int() with base 10: '23.98'
```

**Comment by WyattBlue** [comment]
fixed in 21w51a
