### ISSUE TITLE
ValueError: cannot reshape array of size 2147483647 into shape (2)

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [WyattBlue/auto-editor#226]
(Make sure you're using the latest version)

**What went wrong**
I got the following error:

```
auto-editor "out1.mp4" --constant_rate_factor unset --preset unset --tune unset --video_codec uncompressed
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\auto-editor.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\auto_editor\__main__.py", line 459, in main
    main_loop(input_list, ffmpeg, args, speeds, segments, log)
  File "c:\python38\lib\site-packages\auto_editor\__main__.py", line 440, in main_loop
    cuts, output_path = edit_media(i, inp, ffmpeg, args, progress, speeds,
  File "c:\python38\lib\site-packages\auto_editor\edit.py", line 217, in edit_media
    sample_rate, audio_samples = read(temp_file)
  File "c:\python38\lib\site-packages\auto_editor\scipy\wavfile.py", line 497, in read
    data = _read_data_chunk(fid, format_tag, channels, bit_depth,
  File "c:\python38\lib\site-packages\auto_editor\scipy\wavfile.py", line 405, in _read_data_chunk
    data = data.reshape(-1, channels)
ValueError: cannot reshape array of size 2147483647 into shape (2)
```

This is the video info:
```
auto-editor info out1.mp4
file: out1.mp4
 - video tracks: 1
   - Track #0
     - codec: h264
     - fps: 20
     - resolution: 1968x1124 (492:281)
     - bitrate: 517 kb/s
     - lang: eng
 - audio tracks: 1
   - Track #0
     - codec: aac
     - samplerate: 48000
     - bitrate: 161 kb/s
     - lang: eng
 - container:
   - duration: 07:02:22.04
   - bitrate: 684 kb/s
```
As you can see, this is a long video (more than 7 hours). Will this affect auto-editor? I'm using this version on Windows 10:

```
auto-editor --version
Auto-Editor version 21w51a
```

**Comment by WyattBlue** [comment]
I've pushed the fix to a new version of auto-editor and it should fix this issue.
