### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 

### ISSUE THREAD

**Issue by idMysteries** [WyattBlue/auto-editor#252]
```
Traceback (most recent call last):
  File "d:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Python38\Scripts\auto-editor.exe\__main__.py", line 7, in <module>
  File "d:\python38\lib\site-packages\auto_editor\__main__.py", line 402, in main
    main_loop(input_list, ffmpeg, args, log)
  File "d:\python38\lib\site-packages\auto_editor\__main__.py", line 379, in main_loop
    inp = FileInfo(input_path, ffmpeg)
  File "d:\python38\lib\site-packages\auto_editor\ffwrapper.py", line 139, in __init__
    info = get_stdout([ffmpeg.path, '-hide_banner', '-i', path])
  File "d:\python38\lib\site-packages\auto_editor\utils\func.py", line 13, in get_stdout
    return stdout.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 878: invalid continuation byte
```

Video (10 sec)
https://mega.nz/file/eUdFhSDY#3KmpCpZk6dOZKkByd8LRdPUlEzE4am7iGdHwPJhIgfM

**Comment by WyattBlue** [comment]
What text format is your terminal in?

**Comment by idMysteries** [comment]
> What text format is your terminal in?

Don't know but this error appears in:
mpv (media player) console
cmd.exe
powershell.exe

**Comment by idMysteries** [comment]
Only in this video, works well with other videos

**Comment by WyattBlue** [comment]
It looks like the video's description has an invalid unicode character. All that needs to be changed is for auto-editor to throw that character away.

**Comment by WyattBlue** [comment]
Closing since the commit passed and it fixed the problem on my end. I'll push this to a new release soon.

**Comment by idMysteries** [comment]
Thank you, it works
