### ISSUE TITLE
I can not use audio and motion thresholds  toggled independently,

### ISSUE THREAD

**Issue by lxyer** [WyattBlue/auto-editor#264]
I can not use audio and motion thresholds  toggled independently,

### auto-editor /Users/lxyer/Desktop/test.mp4 --ffmpeg-location '/opt/homebrew/Cellar/ffmpeg/5.0.1-with-options_1/bin/ffmpeg' --edit 'audio:threshold=3% or motion:threshold=0.02%'  --export final-cut-pro

Traceback (most recent call last):                                                                              |    0%  ETA 05:01 PM
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/auto-editor", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/auto_editor/__main__.py", line 473, in main
    main_loop(input_list, ffmpeg, args, log)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/auto_editor/__main__.py", line 453, in main_loop
    cuts, output_path = edit_media(i, inp, ffmpeg, args, progress, TEMP, log)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/auto_editor/edit.py", line 146, in edit_media
    chunks = get_chunks(inp, args, progress, temp, log)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/auto_editor/method.py", line 263, in get_chunks
    has_loud = get_has_loud(args.edit_based_on, inp, progress, temp, log, args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/auto_editor/method.py", line 209, in get_has_loud
    stream_data = get_stream_data(method, attrs, args, inp, progress, temp, log)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/auto_editor/method.py", line 103, in get_stream_data
    return get_audio_list(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/auto_editor/method.py", line 53, in get_audio_list
    audio_list = audio_detection(audio_samples, sample_rate, fps, progress)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/auto_editor/analyze/audio.py", line 38, in audio_detection
    threshold_list[i] = get_max_volume(audio_samples[start:end]) / max_volume
ZeroDivisionError: float division by zero

### auto-editor /Users/lxyer/Desktop/test.mp4 --ffmpeg-location '/opt/homebrew/Cellar/ffmpeg/5.0.1-with-options_1/bin/ffmpeg' --edit motion:threshold=0.02     this is OK

_Originally posted by @lxyer in https://github.com/WyattBlue/auto-editor/issues/263#issuecomment-1108294972_

**Comment by lxyer** [comment]
I found the reason for this problem, because I have no sound in this video, the logic of this piece can add a little verification.

**Comment by WyattBlue** [comment]
I've fixed the divide by zero error in master.
