### ISSUE TITLE
Division by zero exception thrown when given silent audio track

### ISSUE THREAD

**Issue by BigB00st** [WyattBlue/auto-editor#282]
When attempting to edit file by audio given a silent audio track, an exception is thrown instead of exiting gracefully:

Traceback:
```
(env) > auto-editor "file.mp4" --cut_by_this_track 0 --keep_tracks_seperate --margin 7 --no_open --export_to_premiere -o out.xml --silent_threshold 2%
max_volume 0.0udio
Traceback (most recent call last):                                                                                                                                                                                |    0%  ETA 09:58 AM
  File "d:\program files\python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\program files\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Libs\auto-editor-env\Scripts\auto-editor.exe\__main__.py", line 7, in <module>
  File "D:\Libs\auto-editor-env\lib\site-packages\auto_editor\__main__.py", line 412, in main
    main_loop(input_list, ffmpeg, args, segments, log)
  File "D:\Libs\auto-editor-env\lib\site-packages\auto_editor\__main__.py", line 392, in main_loop
    cuts, output_path = edit_media(
  File "D:\Libs\auto-editor-env\lib\site-packages\auto_editor\edit.py", line 234, in edit_media
    chunks = get_chunks(
  File "D:\Libs\auto-editor-env\lib\site-packages\auto_editor\edit.py", line 63, in get_chunks
    has_loud = get_has_loud(inp, args, fps, audio_samples, sample_rate, log)
  File "D:\Libs\auto-editor-env\lib\site-packages\auto_editor\edit.py", line 43, in get_has_loud
    audio_list = audio_detection(audio_samples, sample_rate,
  File "D:\Libs\auto-editor-env\lib\site-packages\auto_editor\analyze\audio.py", line 58, in audio_detection
    if get_max_volume(audio_samples[start:end]) / max_volume > silent_threshold:
ZeroDivisionError: float division by zero
```

This is because max_volume is 0.

**Comment by WyattBlue** [comment]
This was fixed a long time ago.
