### ISSUE TITLE
ValueError: could not broadcast input array from shape (41984,2) into shape (40136,2)

### ISSUE THREAD

**Issue by sasa** [WyattBlue/auto-editor#29]
When using fastVideoPlus.py I get this error:

```
PS C:\Videos\obs> py .\auto-editor.py .\2020-06-28_02-42-54.mkv -s 10 -o out-10.mkv -m 5 --no_open --verbose
Running from fastVideoPlus.py
ffmpeg version 4.2.3 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200523
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, matroska,webm, from '.\2020-06-28_02-42-54.mkv':
  Metadata:
    ENCODER         : Lavf58.29.100
  Duration: 00:00:01.57, start: -0.007000, bitrate: 53 kb/s
    Stream #0:0: Video: h264 (Main), yuv420p(tv, bt470bg/unknown/unknown, progressive), 1280x720 [SAR 1:1 DAR 16:9], 30.30 fps, 30 tbr, 1k tbn, 60 tbc (default)
    Metadata:
      DURATION        : 00:00:01.573000000
    Stream #0:1: Audio: opus, 48000 Hz, mono, fltp (default)
    Metadata:
      DURATION        : 00:00:01.561000000
Stream mapping:
  Stream #0:1 -> #0:0 (opus (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to '.TEMP/output.wav':
  Metadata:
    ISFT            : Lavf58.29.100
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, stereo, s16, 1536 kb/s (default)
    Metadata:
      DURATION        : 00:00:01.561000000
      encoder         : Lavc58.54.100 pcm_s16le
size=     291kB time=00:00:01.56 bitrate=1529.5kbits/s speed= 223x
video:0kB audio:291kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.026151%
Traceback (most recent call last):████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 78.7% done ETA 02:43 AM
  File ".\auto-editor.py", line 260, in <module>
    outFile = fastVideoPlus(INPUT_FILE, newOutput, args.silent_threshold,
  File "C:\Videos\obs\scripts\fastVideoPlus.py", line 157, in fastVideoPlus
    y[yPointer: yPointerEnd] = spedupAudio
ValueError: could not broadcast input array from shape (41984,2) into shape (40136,2)
```

I do not get it when using ` -s 99999`

Also tried other encoders for video and audio.

Run ``auto-editor.py --debug`` and paste the output.

```
Python Version: 3.8.2 64-bit
Platform: Windows
Auto-Editor Version: 20w26a
```

**Comment by WyattBlue** [comment]
I think I know what's causing the bug and it should be a quick fix.

Try [downloading using the experimental version](https://github.com/WyattBlue/auto-editor/archive/experimental.zip) and tell me if you still have that problem.

**Comment by sasa** [comment]
Returns:

```
PS C:\Videos\obs> py .\auto-editor.py .\2020-06-28_02-42-54.mkv -s 10 -o out-10.mkv -m 5 --no_open
Running from fastVideoPlus.py
Traceback (most recent call last):
  File ".\auto-editor.py", line 260, in <module>
    outFile = fastVideoPlus(INPUT_FILE, newOutput, args.silent_threshold,
  File "C:\Videos\obs\scripts\fastVideoPlus.py", line 72, in fastVideoPlus
    chunks = getAudioChunks(audioData, sampleRate, fps, silentThreshold, 2, frameMargin)
TypeError: getAudioChunks() takes 5 positional arguments but 6 were given

```

**Comment by WyattBlue** [comment]
That doesn't make sense, getAudioChunks takes 6 positional arguments. 

```python
def getAudioChunks(audioData, sampleRate, fps, silentT, zoomT, frameMargin):
    audioSampleCount = audioData.shape[0]
    maxAudioVolume = getMaxVolume(audioData)

    samplesPerFrame = sampleRate / fps
    audioFrameCount = int(math.ceil(audioSampleCount / samplesPerFrame))
    hasLoudAudio = np.zeros((audioFrameCount), dtype=np.uint8)

   blah blah blah ...

```

**Comment by sasa** [comment]
Yes, my bad. I only overwrote one file. I replaced everything now, and it worked. Thank you! :-)

**Comment by WyattBlue** [comment]
Thank you.

I'll close this issue when I release the new version.

**Comment by sasa** [comment]
So, there is no error and cutting works, but the video has different results. In the video I count to 5 and with -s 99999 the 5 is still in there, with -s 10 it is only 1 2 3 4. I will prepare an example and try to reproduce it. But maybe you already have an idea.

**Comment by sasa** [comment]
As a matter of fact, there is the error again:

```
PS C:\Videos\obs> py .\auto-editor.py 12345.mkv -s 10 -o 12345-10.mkv -m 5
Running from fastVideoPlus.py
Traceback (most recent call last):██████████████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░] 92.0% done ETA 05:36 AM
  File ".\auto-editor.py", line 268, in <module>
    outFile = fastVideoPlus(INPUT_FILE, newOutput, args.silent_threshold,
  File "C:\Videos\obs\scripts\fastVideoPlus.py", line 158, in fastVideoPlus
    y[yPointer: yPointerEnd] = spedupAudio
ValueError: could not broadcast input array from shape (43008,2) into shape (38879,2)
```

I attached the video
[12345.zip](https://github.com/WyattBlue/auto-editor/files/4841280/12345.zip)

**Comment by WyattBlue** [comment]
I was able to reproduce the error. 

Try downloading the [experimental build](https://github.com/WyattBlue/auto-editor/archive/experimental.zip) again. I made some changes.

**Comment by sasa** [comment]
This one works again. Will let you know if it comes again.

**Comment by WyattBlue** [comment]
I've pushed the new code to master so I'll close this issue

**Comment by Keagel** [comment]
The issue I just encountered is very similar to this one so I don't think I should open a new issue.

Here is the complete debug output:

```
❯ auto-editor "/mnt/d/Users/PC/Videos/2020-12-08 13-29-55.mkv" --edit_based_on audio_or_motion --frame_margin 90 --export_to_premiere --debug

  Exporting to Adobe Premiere Pro XML file.
   - Temp Directory: /tmp/tmp93n_1av2
   - Speeds: [99999, 1.0]
   - INPUT_FILE: /mnt/d/Users/PC/Videos/2020-12-08 13-29-55.mkv
   - newOutput: /mnt/d/Users/PC/Videos/2020-12-08 13-29-55.xml
   - sampleRate: 48000
   - audioBitrate: None
Analyzing audio volume.
Analyzing video motion.
   - Cutting totalFrames: 433921
Traceback (most recent call last):
  File "/home/pc/.local/bin/auto-editor", line 8, in <module>
    sys.exit(main())
  File "/home/pc/.local/lib/python3.8/site-packages/auto_editor/__main__.py", line 427, in main
    hasLoud = combineArrs(audioList, motionList, args.edit_based_on, log)
  File "/home/pc/.local/lib/python3.8/site-packages/auto_editor/cutting.py", line 48, in combineArrs
    hasLoud = audioList | motionList
ValueError: operands could not be broadcast together with shapes (433486,) (433921,)
```

This is a 4 hours long video recorded with OBS without any modification done to it. It has 3 separate audio tracks for what it's worth.

**Comment by WyattBlue** [comment]
@Keagel I released a new version that maybe should fix your issue. Try it again.
 `pip3 install auto-editor -U`

**Comment by Keagel** [comment]
It did fix that error, I have another one now. I'll open a new issue.
