### ISSUE TITLE
Traceback: JSONDecodeError

### ISSUE THREAD

**Issue by ajayrijh** [WyattBlue/auto-editor#319]
Love this tool; but I believe I ran into a bug. Getting a JSON Traceback error after closing the command line while the auto-editor was analyzing a clip. I tried to re-install auto-editor, it's dependencies (ae-ffmpeg, av, numpy,pillow), anaconda, python and perform a system restore but it's still returning the below traceback error:

auto-editor test.mp4

Traceback (most recent call last):
  File "C:\Users\ajayr\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ajayr\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ajayr\anaconda3\Scripts\auto-editor.exe\__main__.py", line 7, in <module>
  File "C:\Users\ajayr\anaconda3\lib\site-packages\auto_editor\__main__.py", line 349, in main
    edit_media(paths, ffmpeg, args, temp, log)
  File "C:\Users\ajayr\anaconda3\lib\site-packages\auto_editor\edit.py", line 255, in edit_media
    timeline = make_timeline(
  File "C:\Users\ajayr\anaconda3\lib\site-packages\auto_editor\timeline.py", line 146, in make_timeline
    chunks, vclips, aclips = make_layers(
  File "C:\Users\ajayr\anaconda3\lib\site-packages\auto_editor\make_layers.py", line 181, in make_layers
    has_loud = run_interpreter(method, filesetup, log)
  File "C:\Users\ajayr\anaconda3\lib\site-packages\auto_editor\make_layers.py", line 100, in run_interpreter
    results = interpreter.interpret()
  File "C:\Users\ajayr\anaconda3\lib\site-packages\auto_editor\interpreter.py", line 1251, in interpret
    return self.visit(self.parser.comp())
  File "C:\Users\ajayr\anaconda3\lib\site-packages\auto_editor\interpreter.py", line 1137, in visit
    return [self.visit(c) for c in node.children]
  File "C:\Users\ajayr\anaconda3\lib\site-packages\auto_editor\interpreter.py", line 1137, in <listcomp>
    return [self.visit(c) for c in node.children]
  File "C:\Users\ajayr\anaconda3\lib\site-packages\auto_editor\interpreter.py", line 1134, in visit
    return edit_method(node.val, self.filesetup)
  File "C:\Users\ajayr\anaconda3\lib\site-packages\auto_editor\analyze.py", line 417, in edit_method
    audio_levels(ensure, src, s, tb, bar, strict, temp, log),
  File "C:\Users\ajayr\anaconda3\lib\site-packages\auto_editor\analyze.py", line 178, in audio_levels
    if (arr := read_cache(src, tb, "audio", {"stream": s}, temp)) is not None:
  File "C:\Users\ajayr\anaconda3\lib\site-packages\auto_editor\analyze.py", line 115, in read_cache
    cache = json.load(file)
  File "C:\Users\ajayr\anaconda3\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\ajayr\anaconda3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\ajayr\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\ajayr\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ajayrijh** [comment]
I had to delete the corrupted file created in my AppData\Local\Temp directory. Works again. Thanks & apologies for raising.
