### ISSUE TITLE
auto-editor meeting_01.mp4 error

### ISSUE THREAD

**Issue by cdfm1026** [WyattBlue/auto-editor#329]
### What's your platform?

```shell
Python Version: 3.9.1 64-bit
Platform: Darwin 21.6.0 arm64
FFmpeg Version: n5.1.1-5.1.1
FFmpeg Path: /opt/homebrew/lib/python3.9/site-packages/ae_ffmpeg/Darwin-arm64/ffmpeg
Auto-Editor Version: 23w04a
```

### Bug description

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/auto-editor", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/auto_editor/__main__.py", line 338, in main
    edit_media(paths, ffmpeg, args, temp, log)
  File "/opt/homebrew/lib/python3.9/site-packages/auto_editor/edit.py", line 259, in edit_media
    tl = make_timeline(
  File "/opt/homebrew/lib/python3.9/site-packages/auto_editor/make_layers.py", line 148, in make_timeline
    chunks, vclips, aclips = make_layers(
  File "/opt/homebrew/lib/python3.9/site-packages/auto_editor/make_layers.py", line 305, in make_layers
    has_loud = run_interpreter(method, filesetup, log)
  File "/opt/homebrew/lib/python3.9/site-packages/auto_editor/make_layers.py", line 113, in run_interpreter
    results = interpreter.interpret()
  File "/opt/homebrew/lib/python3.9/site-packages/auto_editor/interpreter.py", line 1382, in interpret
    result.append(self.visit(self.parser.expr()))
  File "/opt/homebrew/lib/python3.9/site-packages/auto_editor/interpreter.py", line 1177, in visit
    return edit_method(node.val, self.filesetup)
  File "/opt/homebrew/lib/python3.9/site-packages/auto_editor/analyze.py", line 504, in edit_method
    audio_levels(ensure, src, s, tb, bar, strict, temp, log),
  File "/opt/homebrew/lib/python3.9/site-packages/auto_editor/analyze.py", line 238, in audio_levels
    threshold_list[i] = get_max_volume(samples[start:end]) / max_volume
  File "/opt/homebrew/lib/python3.9/site-packages/auto_editor/analyze.py", line 211, in get_max_volume
    return max(float(np.max(s)), -float(np.min(s)))
  File "<__array_function__ internals>", line 200, in amax
  File "/opt/homebrew/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 2820, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/opt/homebrew/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```

**Comment by cdfm1026** [comment]
langxinxingzhe@langxinxingzhedeM1 Python % pip install auto-editor
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: auto-editor in /opt/homebrew/lib/python3.9/site-packages (23.4.1)
Requirement already satisfied: av==10.0.0 in /opt/homebrew/lib/python3.9/site-packages (from auto-editor) (10.0.0)
Requirement already satisfied: numpy>=1.22.0 in /opt/homebrew/lib/python3.9/site-packages (from auto-editor) (1.24.2)
Requirement already satisfied: ae-ffmpeg==1.1.1 in /opt/homebrew/lib/python3.9/site-packages (from auto-editor) (1.1.1)
Requirement already satisfied: pillow==9.4.0 in /opt/homebrew/lib/python3.9/site-packages (from auto-editor) (9.4.0)
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621

**Comment by WyattBlue** [comment]
I'm going to close this because I think either commit cd5382a or ef6a512 should address this traceback. 

I don't like making two releases to close to each-other so ef6a512 will only be in master for at least a week.
