### ISSUE TITLE
ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by xBackward** [WyattBlue/auto-editor#334]
### What's your platform?

```shell
Python Version: 3.11.2 64-bit
Platform: Windows 10 amd64
FFmpeg Version: N-105325-g7512293cf9
FFmpeg Path: C:\Users\CFS\AppData\Local\Programs\Python\Python311\Lib\site-packages\ae_ffmpeg\Windows\ffmpeg.exe
Auto-Editor Version: 23w08a
```

### Bug description

I've honestly never worked with code in general before, so I don't know what the issue was. All I know though, was that it wasn't exporting my video and it just kept giving me this message at the end of the code.

### What command did you use

```shell
auto-editor "C:\Users\CFS\Downloads\com.AnotherAxiom.GorillaTag-20230221-165636.mp4"
```

### Comments

I've literally never done coding before, so this is probably just a really simple issue that I don't know how to fix. Please help lol

**Comment by WyattBlue** [comment]
To effectively address this issue, I need the full traceback with line numbers and everything. Only putting the error message in the title is not enough.

Also, can you post the output of `auto-editor info path-to-your-file.mp4`? This information will help narrow down causes.

**Comment by xBackward** [comment]
C:\Users\CFS>auto-editor "C:\Users\CFS\Downloads\com.AnotherAxiom.GorillaTag-20230221-165636.mp4"
Traceback (most recent call last):                                                                                                          |    0%  ETA 03:43 PM
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\CFS\AppData\Local\Programs\Python\Python311\Scripts\auto-editor.exe\__main__.py", line 7, in <module>
  File "C:\Users\CFS\AppData\Local\Programs\Python\Python311\Lib\site-packages\auto_editor\__main__.py", line 338, in main
    edit_media(paths, ffmpeg, args, temp, log)
  File "C:\Users\CFS\AppData\Local\Programs\Python\Python311\Lib\site-packages\auto_editor\edit.py", line 247, in edit_media
    tl = make_timeline(
         ^^^^^^^^^^^^^^
  File "C:\Users\CFS\AppData\Local\Programs\Python\Python311\Lib\site-packages\auto_editor\make_layers.py", line 138, in make_timeline
    chunks, vclips, aclips = make_layers(
                             ^^^^^^^^^^^^
  File "C:\Users\CFS\AppData\Local\Programs\Python\Python311\Lib\site-packages\auto_editor\make_layers.py", line 277, in make_layers
    has_loud = run_interpreter(method, filesetup, log)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CFS\AppData\Local\Programs\Python\Python311\Lib\site-packages\auto_editor\make_layers.py", line 104, in run_interpreter
    results = interpret(env, parser)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CFS\AppData\Local\Programs\Python\Python311\Lib\site-packages\auto_editor\interpreter.py", line 1663, in interpret
    result.append(my_eval(env, parser.expr()))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CFS\AppData\Local\Programs\Python\Python311\Lib\site-packages\auto_editor\interpreter.py", line 1403, in my_eval
    return edit_method(node.val, env["@filesetup"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CFS\AppData\Local\Programs\Python\Python311\Lib\site-packages\auto_editor\analyze.py", line 484, in edit_method
    stream_data = to_threshold(levels.audio(s), obj["threshold"])
                               ^^^^^^^^^^^^^^^
  File "C:\Users\CFS\AppData\Local\Programs\Python\Python311\Lib\site-packages\auto_editor\analyze.py", line 237, in audio
    threshold_list[i] = get_max_volume(samples[start:end]) / max_volume
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CFS\AppData\Local\Programs\Python\Python311\Lib\site-packages\auto_editor\analyze.py", line 210, in get_max_volume
    return max(float(np.max(s)), -float(np.min(s)))
                     ^^^^^^^^^
  File "<__array_function__ internals>", line 200, in amax
  File "C:\Users\CFS\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\fromnumeric.py", line 2820, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CFS\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: zero-size array to reduction operation maximum which has no identity
![image_2023-02-24_155029677](https://user-images.githubusercontent.com/126226571/221298546-ef65c2cf-ddc0-4b0c-9eed-4dd636fa6728.png)

**Comment by xBackward** [comment]
my bad, also here's what I got from doing info:
C:\Users\CFS>auto-editor info "C:\Users\CFS\Downloads\com.AnotherAxiom.GorillaTag-20230221-165636.mp4"
C:\Users\CFS\Downloads\com.AnotherAxiom.GorillaTag-20230221-165636.mp4:
 - video:
   - track 0:
     - codec: h264
     - fps: 90000
     - resolution: 1920x1080
     - aspect ratio: 16:9
     - pixel aspect ratio: 1:1
     - duration: 1149.846344
     - pix fmt: yuv420p
     - color range: tv
     - color space: smpte170m
     - color primaries: bt470bg
     - color transfer: smpte170m
     - timebase: 1/90000
     - bitrate: 4996982
     - lang: eng
 - audio:
   - track 0:
     - codec: aac
     - samplerate: 48000
     - channels: 1
     - duration: 1149.807583
     - bitrate: 64001
     - lang: eng
 - container:
   - duration: 1149.861000
   - bitrate: 5065173
![image_2023-02-24_155253652](https://user-images.githubusercontent.com/126226571/221298901-4ea2f4f7-3c74-4844-8dd6-20e64a02ede3.png)

**Comment by xBackward** [comment]
Oops just realized that I should've probably sent them in the code format. I can send them again if you need me too

**Comment by WyattBlue** [comment]
So your video is 19 minutes long and the fps is `90000`!??? That is an obscenely high fps. Is that intentional?

**Comment by WyattBlue** [comment]
I think you can get your video working by simply adding the option '-fps 30'. This makes auto-editor output the video at a standard 30 frames per second, instead of its original, excessively high frame rate.

I'll also check for this in code and output an error message that tells exactly what's wrong.
