### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by ClimenteA** [WyattBlue/auto-editor#352]
Using the latest version I got this while running the script over a 26 hours video.

```
Traceback (most recent call last):                                                                                                   
  File "/home/alin/.pyenv/versions/3.11.2/bin/auto-editor", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/alin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/auto_editor/__main__.py", line 347, in main
    edit_media(paths, ffmpeg, args, temp, log)
  File "/home/alin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/auto_editor/edit.py", line 243, in edit_media
    tl = make_timeline(
         ^^^^^^^^^^^^^^
  File "/home/alin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/auto_editor/make_layers.py", line 142, in make_timeline
    chunks, vclips, aclips = make_layers(
                             ^^^^^^^^^^^^
  File "/home/alin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/auto_editor/make_layers.py", line 279, in make_layers
    has_loud = run_interpreter(method, filesetup, log)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/auto_editor/make_layers.py", line 106, in run_interpreter
    results = interpret(env, parser)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/auto_editor/lang/palet.py", line 1254, in interpret
    result.append(my_eval(env, parser.expr()))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/auto_editor/lang/palet.py", line 1046, in my_eval
    return edit_method(node.val, env["@filesetup"], env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/auto_editor/analyze.py", line 523, in edit_method
    stream_data = to_threshold(levels.audio(s), obj["threshold"])
                               ^^^^^^^^^^^^^^^
  File "/home/alin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/auto_editor/analyze.py", line 246, in audio
    sr, samples = read(
```
 
Not a big deal. I could split with ffmpeg the video in smaller chunks and try again and probably it will work.

**Comment by WyattBlue** [comment]
We don't support videos over 24 hours long. See https://auto-editor.com/docs/supported_media
