### ISSUE TITLE
Fail on "vidTracks"

### ISSUE THREAD

**Issue by d-s-t** [WyattBlue/auto-editor#41]
I'm tring to use the software on a video file on the computer but it's fail. I tried also to run the example video and got the same result. the problem on "subprosses" so i tried also to run the command on cmd (I'm using windows) and got "0" as output.

```
>>py auto-editor.py example.mp4

Running from fastVideo.py
Traceback (most recent call last):
  File "auto-editor.py", line 279, in <module>
    outFile = fastVideo(INPUT_FILE, newOutput, args.silent_threshold,
  File "C:\Users\david\Desktop\silence\scripts\fastVideo.py", line 40, in fastVideo
    tracks = vidTracks(videoFile)
  File "C:\Users\david\Desktop\silence\scripts\usefulFunctions.py", line 87, in vidTracks
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE,
  File "C:\Program Files (x86)\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files (x86)\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Run ``auto-editor.py --debug`` and paste the output.

```
[main 2020-07-12T23:01:28.275Z] update#setState idle
(node:12304) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:12304) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:12304) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:12304) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:12304) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:12304) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:12304) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:12304) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:3476) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:3476) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
[main 2020-07-12T23:01:58.295Z] update#setState checking for updates
[main 2020-07-12T23:01:58.400Z] update#setState idle
```

**Comment by WyattBlue** [comment]
What.

Why's debug printing _that_ out. This project doesn't use election. [Election](https://github.com/electron/electron) is used for JavaScript and HTML, not python projects. 

Can you tell me what Python version your have and how you installed it?

**Comment by d-s-t** [comment]
haha in the past i used "virtual studio code" for writing python code, and i install from there the python in addition to regular instalation, I think the cmd is using the one from thr VSD. im tring to uninstall all my python vertions on the computer, install the newest version and try again.. ill let you know what happend.

**Comment by d-s-t** [comment]
All good, the problam was in my python. 
Thank you!
