### ISSUE TITLE
.ts files not supported

### ISSUE THREAD

**Issue by Sneffel** [WyattBlue/auto-editor#423]
**What went wrong**
Any .ts video crashes no matter what

**Command:**
@echo off
set "input_file=%~1"
"C:\Users\Bruno\AppData\Local\Programs\Python\Python312\Scripts\auto-editor.exe" --margin 2s,3sec --no-open "%input_file%" --my-ffmpeg -c:v libx264 -b:v unset --extras "-preset slow -crf 22"
pause

**Output:**
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Me\AppData\Local\Programs\Python\Python312\Scripts\auto-editor.exe\__main__.py", line 7, in <module>
  File "C:\Users\Me\AppData\Local\Programs\Python\Python312\Lib\site-packages\auto_editor\__main__.py", line 327, in main
    edit_media(paths, ffmpeg, args, temp, log)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python312\Lib\site-packages\auto_editor\edit.py", line 184, in edit_media
    sources = [initFileInfo(path, ffmpeg, log) for path in paths]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\Programs\Python\Python312\Lib\site-packages\auto_editor\ffwrapper.py", line 239, in initFileInfo
    raise e
  File "C:\Users\Me\AppData\Local\Programs\Python\Python312\Lib\site-packages\auto_editor\ffwrapper.py", line 237, in initFileInfo
    _sar, c_range, c_space, c_primary, c_transfer = _raw.strip().split("\n")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 5)

**Comment by WyattBlue** [comment]
I can replicate this using example.mp4. Thanks for the report, I'll look into it.

**Comment by WyattBlue** [comment]
I fixed the bug. You can either use master or wait till the release.
