### ISSUE TITLE
Memory allocation failure

### ISSUE THREAD

**Issue by d-s-t** [WyattBlue/auto-editor#46]
the problem occurs few cases:
1. when running big file like 2+ hours long
2. when running over a folder, happened for me just once and was on the 10th file

```
Traceback (most recent call last):
  File "auto-editor.py", line 279, in <module>
    outFile = fastVideo(INPUT_FILE, newOutput, args.silent_threshold,
  File "C:\Users\avivs\Desktop\auto-editor-master\scripts\fastVideo.py", line 61, in fastVideo
    __, audioData = read(f'{TEMP}/{i}.wav')
  File "C:\Users\avivs\Desktop\auto-editor-master\scripts\wavfile.py", line 513, in read
    data = _read_data_chunk(fid, format_tag, channels, bit_depth,
  File "C:\Users\avivs\Desktop\auto-editor-master\scripts\wavfile.py", line 404, in _read_data_chunk
    data = numpy.fromfile(fid, dtype=dtype, count=n_samples)
MemoryError: Unable to allocate 560. MiB for an array with shape (293801902,) and data type int16
```

Run ``auto-editor.py --debug`` and paste the output.

```
Python Version: 3.8.1 32-bit
Platform: Windows
Auto-Editor Version: 20w28a
```

**Comment by d-s-t** [comment]
I don't know if it's connected but something weird just happened.

I tryed to run again the 10th file alone and after it finished, instead of writing the data to a file it's looks like it's writing the data on the screen.

this what I got:

```
stream #0:
  keyframe=0
  duration=0.033
  dts=271.867  pts=271.867
  size=3815
00000000  00 00 01 b6 5d 60 33 ff ff ff ff ff ff ff ff ff ....]`3.........
```
. 
. 
. 
```
00000ed0  ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ................
00000ee0  ff ff ff ff ff ff fd                            .......
stream #0:
  keyframe=1
  duration=0.021
  dts=271.915  pts=271.915
  size=4096
00000000  76 fe 76 fe 87 fe 87 fe a0 fe a0 fe 8f fe 8f fe v.v.............
00000010  9f fe 9f fe ae fe ae fe ba fe ba fe e0 fe df fe ................
```
. 
. 
. 
```
00000fd0  2b ff 2b ff 07 ff 07 ff dd fe dd fe a7 fe a7 fe +.+.............
00000fe0  85 fe 85 fe 7f fe 7e fe 50 fe 4f fe 33 fe 33 fe ......~.P.O.3.3.
00000ff0  29 fe 29 fe 1c fe 1c fe 25 fe 25 fe 0c fe 0d fe ).).....%.%.....

Enter command: <target>|all <time>|-1 <command>[ <argument>]
```


(was more in the top but it cutted out from the terminal)

**Comment by WyattBlue** [comment]
The problem is that you have the 32-bit of Python. You need to upgrade to 64-bit by reinstalling to work.
