### ISSUE TITLE
1st launch , don't work

### ISSUE THREAD

**Issue by flover2102** [WyattBlue/auto-editor#477]
(Make sure you're using the latest version)

**What went wrong**

```
E:\+video\autre>auto-editor 9e703524.mp4
Traceback (most recent call last):                                                                                                                                                                                |    0%  ETA 04:47 PM
  File "c:\users\a\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\a\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\a\AppData\Local\Programs\Python\Python39\Scripts\auto-editor.exe\__main__.py", line 7, in <module>
  File "c:\users\a\appdata\local\programs\python\python39\lib\site-packages\auto_editor\__main__.py", line 347, in main
    edit_media(paths, ffmpeg, args, temp, log)
  File "c:\users\a\appdata\local\programs\python\python39\lib\site-packages\auto_editor\edit.py", line 243, in edit_media
    tl = make_timeline(
  File "c:\users\a\appdata\local\programs\python\python39\lib\site-packages\auto_editor\make_layers.py", line 142, in make_timeline
    chunks, vclips, aclips = make_layers(
  File "c:\users\a\appdata\local\programs\python\python39\lib\site-packages\auto_editor\make_layers.py", line 279, in make_layers
    has_loud = run_interpreter(method, filesetup, log)
  File "c:\users\a\appdata\local\programs\python\python39\lib\site-packages\auto_editor\make_layers.py", line 106, in run_interpreter
    results = interpret(env, parser)
  File "c:\users\a\appdata\local\programs\python\python39\lib\site-packages\auto_editor\lang\palet.py", line 1449, in interpret
    result.append(my_eval(env, parser.expr()))
  File "c:\users\a\appdata\local\programs\python\python39\lib\site-packages\auto_editor\lang\palet.py", line 1207, in my_eval
    return edit_method(node.val, env["@filesetup"], env)
  File "c:\users\a\appdata\local\programs\python\python39\lib\site-packages\auto_editor\analyze.py", line 540, in edit_method
    stream_data = to_threshold(levels.audio(s), obj["threshold"])
  File "c:\users\a\appdata\local\programs\python\python39\lib\site-packages\auto_editor\analyze.py", line 294, in audio
    threshold_list = np.zeros((audio_ticks), dtype=np.float_)
  File "c:\users\a\appdata\local\programs\python\python39\lib\site-packages\numpy\__init__.py", line 426, in __getattr__
    raise AttributeError(
AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.

```

**Comment by WyattBlue** [comment]
Use the latest release of auto-editor.

**Comment by flover2102** [comment]
i did "pip install auto-editor" and i alredy try to do "pip install auto-editor --upgrade"

i should be update

**Comment by WyattBlue** [comment]
you also need to install a newer version of Python.

**Comment by flover2102** [comment]
thx it was that

**Comment by flover2102** [comment]
how i do if my video have 2 audio track and i want to cut only on 2nd track silent ?

**Comment by WyattBlue** [comment]
```
auto-editor video.mp4 --edit audio:stream=1
```
