### ISSUE TITLE
AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.

### ISSUE THREAD

**Issue by AlexandrosTsag** [WyattBlue/auto-editor#486]
### Bug description

(base) alexandrostsagkarakis@192 Μαθηματικά Γ Γυμνασίου % auto-editor 1.wav --edit audio:4% --export final-cut-pro
Traceback (most recent call last):                                       |    0%  ETA 21:49       
  File "/Users/alexandrostsagkarakis/Library/Python/3.9/bin/auto-editor", line 8, in <module>
    sys.exit(main())
  File "/Users/alexandrostsagkarakis/Library/Python/3.9/lib/python/site-packages/auto_editor/__main__.py", line 347, in main
    edit_media(paths, ffmpeg, args, temp, log)
  File "/Users/alexandrostsagkarakis/Library/Python/3.9/lib/python/site-packages/auto_editor/edit.py", line 243, in edit_media
    tl = make_timeline(
  File "/Users/alexandrostsagkarakis/Library/Python/3.9/lib/python/site-packages/auto_editor/make_layers.py", line 142, in make_timeline
    chunks, vclips, aclips = make_layers(
  File "/Users/alexandrostsagkarakis/Library/Python/3.9/lib/python/site-packages/auto_editor/make_layers.py", line 279, in make_layers
    has_loud = run_interpreter(method, filesetup, log)
  File "/Users/alexandrostsagkarakis/Library/Python/3.9/lib/python/site-packages/auto_editor/make_layers.py", line 106, in run_interpreter
    results = interpret(env, parser)
  File "/Users/alexandrostsagkarakis/Library/Python/3.9/lib/python/site-packages/auto_editor/lang/palet.py", line 1449, in interpret
    result.append(my_eval(env, parser.expr()))
  File "/Users/alexandrostsagkarakis/Library/Python/3.9/lib/python/site-packages/auto_editor/lang/palet.py", line 1207, in my_eval
    return edit_method(node.val, env["@filesetup"], env)
  File "/Users/alexandrostsagkarakis/Library/Python/3.9/lib/python/site-packages/auto_editor/analyze.py", line 540, in edit_method
    stream_data = to_threshold(levels.audio(s), obj["threshold"])
  File "/Users/alexandrostsagkarakis/Library/Python/3.9/lib/python/site-packages/auto_editor/analyze.py", line 294, in audio
    threshold_list = np.zeros((audio_ticks), dtype=np.float_)
  File "/Users/alexandrostsagkarakis/Library/Python/3.9/lib/python/site-packages/numpy/__init__.py", line 397, in __getattr__
    raise AttributeError(
AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.
(base) alexandrostsagkarakis@192 Μαθηματικά Γ Γυμνασίου % 

### What's your platform?

```shell
(base) alexandrostsagkarakis@192 Μαθηματικά Γ Γυμνασίου % auto-editor 1.wav --edit audio:4% --export final-cut-pro
Traceback (most recent call last):                                       |    0%  ETA 21:49       
  File "/Users/alexandrostsagkarakis/Library/Python/3.9/bin/auto-editor", line 8, in <module>
    sys.exit(main())
  File "/Users/alexandrostsagkarakis/Library/Python/3.9/lib/python/site-packages/auto_editor/__main__.py", line 347, in main
    edit_media(paths, ffmpeg, args, temp, log)
  File "/Users/alexandrostsagkarakis/Library/Python/3.9/lib/python/site-packages/auto_editor/edit.py", line 243, in edit_media
    tl = make_timeline(
  File "/Users/alexandrostsagkarakis/Library/Python/3.9/lib/python/site-packages/auto_editor/make_layers.py", line 142, in make_timeline
    chunks, vclips, aclips = make_layers(
  File "/Users/alexandrostsagkarakis/Library/Python/3.9/lib/python/site-packages/auto_editor/make_layers.py", line 279, in make_layers
    has_loud = run_interpreter(method, filesetup, log)
  File "/Users/alexandrostsagkarakis/Library/Python/3.9/lib/python/site-packages/auto_editor/make_layers.py", line 106, in run_interpreter
    results = interpret(env, parser)
  File "/Users/alexandrostsagkarakis/Library/Python/3.9/lib/python/site-packages/auto_editor/lang/palet.py", line 1449, in interpret
    result.append(my_eval(env, parser.expr()))
  File "/Users/alexandrostsagkarakis/Library/Python/3.9/lib/python/site-packages/auto_editor/lang/palet.py", line 1207, in my_eval
    return edit_method(node.val, env["@filesetup"], env)
  File "/Users/alexandrostsagkarakis/Library/Python/3.9/lib/python/site-packages/auto_editor/analyze.py", line 540, in edit_method
    stream_data = to_threshold(levels.audio(s), obj["threshold"])
  File "/Users/alexandrostsagkarakis/Library/Python/3.9/lib/python/site-packages/auto_editor/analyze.py", line 294, in audio
    threshold_list = np.zeros((audio_ticks), dtype=np.float_)
  File "/Users/alexandrostsagkarakis/Library/Python/3.9/lib/python/site-packages/numpy/__init__.py", line 397, in __getattr__
    raise AttributeError(
AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.
(base) alexandrostsagkarakis@192 Μαθηματικά Γ Γυμνασίου %
```

### What command did you use

```shell
auto-editor 1.wav --edit audio:4% --export final-cut-pro
```

### What properties does your input video have?

(base) alexandrostsagkarakis@192 Μαθηματικά Γ Γυμνασίου % auto-editor info 1.wav                                                                         
1.wav:
 - audio:
   - track 0:
     - codec: pcm_s24le
     - samplerate: 48000
     - channels: 2
     - duration: 436.411479
     - bitrate: 2304000
 - container:
   - duration: 436.411479
   - bitrate: 2304075

(base) alexandrostsagkarakis@192 Μαθηματικά Γ Γυμνασίου % ffmpeg -hide_banner -i 1.wav                                                                   
Input #0, wav, from '1.wav':
  Duration: 00:07:16.41, bitrate: 2304 kb/s
  Stream #0:0: Audio: pcm_s24le ([1][0][0][0] / 0x0001), 48000 Hz, stereo, s32 (24 bit), 2304 kb/s
At least one output file must be specified

**Comment by AlexandrosTsag** [comment]
I opened the file in a text editor, located line 294, and changed:

threshold_list = np.zeros((audio_ticks), dtype=np.float_)

to:

threshold_list = np.zeros((audio_ticks), dtype=np.float64)

This resolved the error.

**Comment by WyattBlue** [comment]
This was fixed a while ago. If you upgrade Python 3.9, you'll get the latest auto-editor versions.
