### ISSUE TITLE
WavError: File format b'' not supported

### ISSUE THREAD

**Issue by utopiatopia** [WyattBlue/auto-editor#553]
File available [here](https://ible.page/video/working.mkv).

```
$ auto-editor out.mkv -v 2 -s 8 -o out2.mkv              
Traceback (most recent call last):                    |  0.2%  ETA 19:52       
  File "/Users/utopiatopia/.local/bin/auto-editor", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/utopiatopia/.local/pipx/venvs/auto-editor/lib/python3.12/site-packages/auto_editor/__main__.py", line 339, in main
    edit_media(paths, ffmpeg, args, log)
  File "/Users/utopiatopia/.local/pipx/venvs/auto-editor/lib/python3.12/site-packages/auto_editor/edit.py", line 353, in edit_media
    make_media(tl, output)
  File "/Users/utopiatopia/.local/pipx/venvs/auto-editor/lib/python3.12/site-packages/auto_editor/edit.py", line 285, in make_media
    audio_output = make_new_audio(tl, ensure, args, ffmpeg, bar, log)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/utopiatopia/.local/pipx/venvs/auto-editor/lib/python3.12/site-packages/auto_editor/render/audio.py", line 282, in make_new_audio
    clip_arr = process_audio_clip(clip, samp_list, samp_start, samp_end, sr)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/utopiatopia/.local/pipx/venvs/auto-editor/lib/python3.12/site-packages/auto_editor/render/audio.py", line 229, in process_audio_clip
    return read(output_bytes)[1]
           ^^^^^^^^^^^^^^^^^^
  File "/Users/utopiatopia/.local/pipx/venvs/auto-editor/lib/python3.12/site-packages/auto_editor/wavfile.py", line 209, in read
    raise WavError(f"File format {file_sig!r} not supported.")
auto_editor.wavfile.WavError: File format b'' not supported.
```

**Comment by WyattBlue** [comment]
I can't replicate this. I think you're using an older version

**Comment by utopiatopia** [comment]
I don't believe that it's just an older version. While getting information about #531, I updated to 25.3.0 to confirm that the issue was still present. This hampered my ability to get more information, however I already had the information. I needed.

**Comment by WyattBlue** [comment]
Did you upgrade with `pipx upgrade-all` ?

**Comment by utopiatopia** [comment]
Yes, I did.

**Comment by WyattBlue** [comment]
run `auto-editor --debug` again please

**Comment by utopiatopia** [comment]
```
$ auto-editor --debug
OS: Darwin 24.1.0 arm64
Python: 3.12.6
PyAV: 13.0.0 (LGPL version 3 or later)
Auto-Editor: 25.3.0
```

**Comment by WyattBlue** [comment]
My debug is:
```
OS: Darwin 23.6.0 arm64
Python: 3.12.7
PyAV: 13.0.0 (LGPL version 3 or later)
Auto-Editor: 25.3.0
```
I don't want to upgrade MacOS right now. I don't see any other differences in my setup.

**Comment by WyattBlue** [comment]
Try installing the latest ffmpeg, then run your command with the `--my-ffmpeg` flag and if it's different.

**Comment by utopiatopia** [comment]
Used Homebrew's latest ffmpeg (7.1) and it's the same error message.

**Comment by WyattBlue** [comment]
Then I'm out of ideas for today

**Comment by WyattBlue** [comment]
When I figured out that `out.mkv` was created with:
```bash
auto-editor working.mkv -o out.mkv
# not from $ cp working.mkv out.mkv
```
I was able to replicate your error.
